version: "3"
services:
  app:
    build: .
    environment:
      PORT: 8001
      HOST: "0.0.0.0"
      USERNAME: "admin"
      PASSWORD: "password"
      DB_HOST: host.docker.internal
      DB_PORT: "5432"
      DATABASE: "pg_db"
      REDIS_PORT: 6379
      REDIS_HOST: host.docker.internal
    command: python main.py
    ports:
      - "8081:8001"
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "pg_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./src/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7.2
    restart: always
    environment:
      REDIS_PASSWORD: "password"
      REDIS_DATABASES: 16
      REDIS_PORT: 6379
    volumes:
      - ./db_redis:/root/redis
    ports:
      - "6379:6379"
